<?php

/**
 * @file
 * RESTful token authentication.
 */


/**
 * Implements hook_menu().
 */
function restful_token_auth_menu() {
  if (!$path = variable_get('restful_token_auth_plugin_menu_item', 'api/login/token')) {
    // Menu item was disabled, and may be declared by an implementing module.
    return;
  }


  $items[$path] = array(
    'title' => 'Login',
    'description' => 'Login with an access token response.',
    'access callback' => 'user_is_anonymous',
    'page callback' => 'restful_menu_process_callback',
    'page arguments' => array('1', 'token_auth'),
  );

  return $items;
}


/**
 * Implements hook_ctools_plugin_directory().
 */
function restful_token_auth_ctools_plugin_directory($module, $plugin) {
  if ($module == 'restful') {
    return 'plugins/' . $plugin;
  }
}


/**
 * Implements hook_entity_info().
 */
function restful_token_auth_entity_info() {
  $items['restful_token_auth'] = array(
    'label' => t('Authentication token'),
    'entity class' => 'RestfulTokenAuth',
    'controller class' => 'EntityAPIController',
    'base table' => 'restful_token_auth',
    'fieldable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'label' => 'name',
      'bundle' => 'type',
    ),
    'bundles' => array(),
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'module' => 'restful_token_auth',
    'entity cache' => module_exists('entitycache'),
  );

  return $items;
}

/**
 * Implements hook_cron().
 *
 * Delete expired token auth entities.
 */
function restful_token_auth_cron() {
  if (!variable_get('restful_token_auth_delete_expired_tokens', TRUE)) {
    // We should not delete expired tokens.
    return;
  }

  $query = new EntityFieldQuery();
  $result = $query
    ->entityCondition('entity_type', 'restful_token_auth')
    ->propertyCondition('expire', REQUEST_TIME, '<')
    ->range(0, 50)
    ->execute();

  if (empty($result['restful_token_auth'])) {
    // No expired tokens.
    return;
  }

  $ids = array_keys($result['restful_token_auth']);
  entity_delete_multiple('restful_token_auth', $ids);
}
