<?php

$plugin = array(
  'label' => t('Restful Test Field Translatable Entity'),
  'description' => t('Export Restful Test Field Translatable Entities.'),
  'resource' => 'restful_test_field_translatable_entity',
  'name' => 'restful_test_field_translatable_entity__1_0',
  'entity_type' => 'restful_test_translatable_entity',
  'bundle' => 'restful_test_translatable_entity',
  'class' => 'RestfulTestTranslatableEntityResource__1_0',
  'field_translate_available' => TRUE,
);
