<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML+RDFa 1.0//EN"
  "http://www.w3.org/MarkUp/DTD/xhtml-rdfa-1.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php print $language->language; ?>" version="XHTML+RDFa 1.0">

<head>
  <title><?php print $head_title; ?></title>
  <?php print $styles; ?>
  <?php print $scripts; ?>
</head>
<body class="angular-example">
<h1>RESTful Angular example.</h1>
<p><em>NOTE:</em> This page is served by Drupal for convenience, but all the content is generated by an AngularJS app.</p>
<?php
if (!empty($page['message'])):
  foreach($page['message'] as $type => $message):
    ?>
    <div class="messages <?php print $type; ?>">
      <ul>
        <?php foreach($message as $msg): ?>
          <li><?php print $msg; ?></li>
        <?php endforeach; ?>
      </ul>
    </div>
  <?php
  endforeach;
endif; ?>

<?php print $content; ?>
</body>
</html>
